# Generated by Django 2.1.2 on 2018-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_auto_20181127_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
