# Generated by Django 2.1.2 on 2018-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_auto_20181128_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='lName',
        ),
        migrations.AddField(
            model_name='like',
            name='email',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
