# Generated by Django 2.1.2 on 2018-11-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_auto_20181128_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
