# Generated by Django 2.1.2 on 2018-11-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
