# Generated by Django 2.1.2 on 2018-12-01 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
