# Generated by Django 2.1.2 on 2018-12-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_like_dtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
