# Generated by Django 2.1.2 on 2018-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0033_auto_20181212_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('hobbyName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hobbyInfo', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('dtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_images')),
                ('hobbies', models.ManyToManyField(to='MainApp.Hobby')),
                ('likes', models.ManyToManyField(to='MainApp.Like')),
            ],
        ),
    ]
